name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Set up .NET
      uses: xt0rted/setup-dotnet@v1.0.0
      with:
        dotnet-version: 6.0.201
    - uses: actions/setup-node@v3
    - run: dotnet build
    - name: install and build npm
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build
    - name: run c# tests
      run: dotnet test
    - name: run TypeScript tests
      working-directory: ./DotnetTemplate.Web
      run: npm t
    - name: run linting
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
    - name: Slack Notification
    - uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: Hello, Slack!